name: Scrape latest data

on:
    push:
    workflow_dispatch:
    schedule:
        - cron: "6,26,46 * * * *" # At minute 6, 26, and 46

jobs:
    scheduled:
        runs-on: ubuntu-latest
        steps:
            - name: Check out this repo
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  pipx install datasette

            - name: Set up python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.11

            - name: Get latest artifact run id
              run: |
                  ARTIFACT_RUN_ID=$(curl -s "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?per_page=1" | jq '.artifacts[0].workflow_run.id')
                  echo "artifact_run_id=$ARTIFACT_RUN_ID" >> $GITHUB_ENV

            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: ca-fires-history-db
                  path: ./data/
                  run-id: ${{ env.artifact_run_id }}
                  github-token: ${{ secrets.GH_PAT  }}
              continue-on-error: true

            - name: Display downloaded file
              run: ls data/

            - name: Run scrape.py
              run: python3 scrape.py

            - name: Upload updated artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ca-fires-history-db
                  path: ./data/fires.db
                  if-no-files-found: error

            - name: Deploy to vercel
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
              run: |-
                  datasette install datasette-publish-vercel
                  datasette publish vercel data/fires.db  --project=ca-fires-history-db --install=datasette-hashed-urls --install=datasette-cluster-map --token="$VERCEL_TOKEN" --metadata data/metadata.json --setting allow_download off  --setting allow_csv_stream off  --setting max_csv_mb 0 --extra-options "-i"
